### PR TITLE
refactor the codes for loading the data and create separate files sto…

### PR DESCRIPTION
**Pull request by jh22d**
…ring the extra codes

### CODE REVIEW

**Comment by miniatureseal** [comment]
Hi Stella, can you please pull the newest changes from github, merge them and accordingly refresh your PR? Thanks!

**Comment by jh22d** [comment]
I have merged my changes with the newest version, and please have another look at it

**Comment by miniatureseal** [comment]
Hi Stella, the branch still has merge conflicts. You need to solve them before we can merge this PR.

Also, the tests need to go in a separate file and into the test folder. How than can be done you can see in the already existing tests.

**Comment by jh22d** [comment]
to fix the merge conflict, i create another pr to do the same task more clearly

**Pull request closed without merging**
